infisical_secrets:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:G4kARq5vMT2ZBs99Jn0hQ1gBI23mZ1C0WWNI/WDITk8=,iv:IMACFl9KbrQMLXSkgKX86hy3TU0EFvWVHAZTYq4x4uw=,tag:OOaiAlsS85pne4sdMrnNUg==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:DOYUO0bdtXsqg+XM9YbbfxvWlg8pZkg2jLY/T7JOKzBVOom3YuqC75qMjSYuBVzJzcWaxy0wgwrtzPWtMdH4rg==,iv:n95JWsiegjxNvG2jqpaEx9M3PvQOGFSn7ONly+ecRmg=,tag:BX9KuVdeGzDlCQO9QOgsiw==,type:str]
    SITE_URL: ENC[AES256_GCM,data:vOkzjWGGkVsvzrH1icHT5CDmLqdDi707gaffHKzi,iv:Kyw5924perJejIQkLG6k2W0m/vWwdhNI0zv24dXn0hk=,tag:ZdQE+mq3KjMrXJbfKhY0lw==,type:str]
sops:
    age:
        - recipient: age1fya5ptcuwkv3fts9pstep82juz6eam2rs6xr6ujkzmq5tp6k2p4qn7h5rw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RGROeUFmeVN5Qmo0Mkov
            QWMxcWJlbVFNL0kvaTBpckpSdiszbHhGQWcwCmI1SCtZc3N0d05FSTZXaWtYOENF
            UGc1N1FEeWwxVnZaZGgvR1BUb3VkZmsKLS0tIG5zWTE1Zk1xTHdCcmxWQjRRS05K
            UUJvS2JXNzJhOUwrdVJDNFZLWHREencK9diK4XtOOFUR552dH3k46v2RXy3+x5DT
            WIok3/CUmIraNxtzqefXFa7WnCVDyAeYvAfn2edt2EAhrNeX8cXZig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T18:20:07Z"
    mac: ENC[AES256_GCM,data:BOQZoTuIYRinqlaldkeiHWcCuotuKf94rSL4NBgGOjwr49AyvZRR9sp8bHom+h2usMFBs0qpTW4YaHC0BiTinKeMOAF+vNcOmC3t3+8VEpw7i0AcvfgsbGUwZcGgofIV/MkuhGaPByQov7jwYP8VhLRC89EMtDNmhb6VL0Clw/A=,iv:Qf5GNXaS1eaLaHUanjBgXhvpL/oKHfUhf6h3AY72lH4=,tag:9CSJ2BJcBmMsCjZ9SQ/Nkw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
