repositories:
 - name: bitwarden
   url: https://charts.bitwarden.com/

releases:
- name: bitwarden
  namespace: security
  chart: bitwarden/sm-operator
- name: pihole
  namespace: security
  chart: ../pihole
  values:
  - ./values/pihole.yaml
  secrets:
  - ./values/pihole-secret.yaml