apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pihole-web-route
spec:
  parentRefs:
  - name: main-gateway
    namespace: traefik
  hostnames:
  - "pihole.alstrom.home.arpa"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: pihole-web
      port: 80