apiVersion: v1
kind: Secret
metadata:
  name: pihole-secret
  namespace: pihole
type: Opaque
stringData:
    #ENC[AES256_GCM,data:dh3o3TiHr9MjiTI83w+3azfLkcnlN/W3oaPngvIamnghR7vFLCnUQfCcgvtob1t6FXABpSR8Mg==,iv:82rd715lRt8rLG8+L8NFPILGEOeM7E3spzQ/Q6ecbvQ=,tag:p2uDpkNHsZD4X1EXNLSaiA==,type:comment]
    password: ENC[AES256_GCM,data:QovxvS7i,iv:H3dwydhqaJvhBlEU9XMxk6Kl87S7SSSSUtr9SfLLrTM=,tag:bm4FG5y5JR8nNQbbphPsDg==,type:str]
sops:
    age:
        - recipient: age1fya5ptcuwkv3fts9pstep82juz6eam2rs6xr6ujkzmq5tp6k2p4qn7h5rw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TTNjZC85T2ZsL0VXM3Ns
            WGpMczB3WTcyMmRXbEFKSHRadjZyUk95YlFFCjBBaHh2WVZoTTUwdXJSdmgycGhF
            bDNib3N0Wll4WHZzemJGZDFmeGxtOGcKLS0tIDFhamd3T2pZZlVCRkJ0RStWUWJU
            Q0dKTmgydHFlUzYvQkdybVg3amdrdlkKkcjBgxn4JZqJ0RutfPlwMDS32ac8Euyd
            GhnLwSIrBD0cJhs9aSrY31J02ZpIL0vwjwySp609oO3RmqY+MFmnQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T16:36:05Z"
    mac: ENC[AES256_GCM,data:lxecMxgVntKe6yL2svKZGkxLBtNGKylJ+0PBLMhdTt2ttzsr0vKcMnlo5MmeWo+dBTFU/7da971BD8F9iVSP9vxqBC2jofamX43Ot0EBZSTktg2ebFFiOiEzdPRF6XVhiuoi+MSH/8b5iaA5Zgazd2z5eeDmHiohvN1Jel5nY2g=,iv:KN746b3oVlaH9nxb2VA3lt0Xb+D6y++vMffssF8g2tY=,tag:VeVYJydaKPdXeBa6Ricgkg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
