apiVersion: ENC[AES256_GCM,data:Qr8=,iv:T7z1sbxoEvjp2k9YcChjklBaEk+/6xnUfCNPjK4leMk=,tag:7YFH1BEqHvRb0+BmBqz3nA==,type:str]
kind: ENC[AES256_GCM,data:FBC3rIA1,iv:iLqX/hUNgZqR883iHjsbnvVNa1jAe+fcucg7Zqx76sc=,tag:VbOne6VJw7yNaczUYDwERw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:40CvhXVsvggcJQo+Tg==,iv:iUggoBwCrVXafL9fJ+RUjSjs49Mk4qgAbZoI4n4Bx0w=,tag:a1ACcXvccMCfIHgA5STBUQ==,type:str]
type: ENC[AES256_GCM,data:AmNM6hBM,iv:a80o5NO/vjbAxvaTnu1Ey3tVEdXEDFEbyP77hr2ykkc=,tag:A7ucE7tl6zEHtpEI4zjHKA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:76KaL4Q7FtiOEsztXzY=,iv:FKdHny1zgHx0IS7qyzjGTKBBcGHI6Bx5ShlUqyWdRno=,tag:IfzTvE5sidcXpw23V1PDzg==,type:str]
sops:
    age:
        - recipient: age1fya5ptcuwkv3fts9pstep82juz6eam2rs6xr6ujkzmq5tp6k2p4qn7h5rw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNU2lFVmNoZkk2TmdISDdC
            TnI5MFV2c3MyQk1FbUJIUDV1VHl0eUN2QWprCjA2b0JGajJNNG5kc0FOUTE1UDBT
            NVRsV2ZLaW9pWENsOFJrL21jUzdMeVUKLS0tIGdzZUVUWWNBTjBJUzQ5cUk4dlZ0
            WE96ZFVHOUdYby9XUm1teHJ4eXlZQ00KfSh5htETJnx+/k+WtqZYCXyTuTAhKlfa
            n+lR9YKNzfhTRuSG5zJKdekI2A5D2bpekxN8bkxqo7sNM4i5iyqOLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T16:47:04Z"
    mac: ENC[AES256_GCM,data:Q9TT52PVMbvpLGuG7xJRJ6atYfiEJsgRG2TpuWiiyg271iF2pSBP7ukUXRSLHhW85TP3nFNDIxS106EUPTCBs8nWfaJG3EJoCiVTKIbHyxvTRFxqQKBDWiLHzAQZW/KxQoKaNyyzPwI7IG577RfU4s/Y2iPH8iizARv+3CbWR58=,iv:v684WJu8MSz7GAv2Ws95gSpdAC/d3yQB2z+fKGqBPrg=,tag:pVXRcAfVpaWp7l2BKJ2+FQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
